default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fukumomolog_db_dev
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: fukumomolog_db_test
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_DB'] %>

production:
  url: <%= ENV.fetch("DATABASE_URL") %>
